-- One row per canonical name.
--
-- Nothing enforced this, and `add_fragrance` is a plain INSERT, so the
-- same bottle could exist twice. That is not theoretical: on 2026-08-11
-- auto-curation wrote "Armaf Club De Nuit Intense" alongside the
-- hand-curated "Armaf Club de Nuit Intense Man" that already answered to
-- that name, and separately re-added a row that had been removed hours
-- earlier. Both split every edge on the bottle, and neither was visible
-- until someone read the file.
--
-- The application-level guards added the same day (`enrich.claimed_names`
-- for aliases and de-branded forms, `corpus.extra_fragrances` for drift)
-- catch the cases they know about. This catches the rest, at the only
-- layer that cannot be bypassed by a new code path.
--
-- Case-insensitive because "Armaf Club De Nuit" and "Armaf Club de Nuit"
-- are one bottle. It does not normalise punctuation or spacing —
-- `normalize_name` does that, and encoding it here would mean rebuilding
-- the index every time that function learned a new rule. This is the
-- floor, not the whole policy.
--
-- SQLite spelled this `COLLATE NOCASE`, which is a property of the
-- column. Postgres has no case-insensitive collation by default, so the
-- same rule becomes an index on an expression — `lower(canonical_name)`.
-- Two consequences worth knowing before you rely on it:
--
--   * The uniqueness is on the *expression*. A query has to say
--     `WHERE lower(canonical_name) = lower(%s)` to use this index;
--     `WHERE canonical_name = %s` will not.
--   * `lower()` is locale-dependent. For ASCII fragrance names that is
--     invisible; it would not be for a Turkish dotless i.
CREATE UNIQUE INDEX IF NOT EXISTS idx_fragrances_canonical_name
    ON fragrances (lower(canonical_name));
