-- Attribution that a machine inferred, kept apart from attribution a
-- commenter stated.
--
-- `claims.subject_frag_id` means one thing and must keep meaning it: the
-- commenter named this bottle and the resolver matched the name they typed.
-- Roughly two thirds of unary claims have it NULL, because people writing
-- under a review say "this" and "it" — they are not being careless, the
-- video already said which bottle.
--
-- Those claims can often be attributed from what the video is about. That
-- is an inference, it is wrong about one time in twenty, and writing it
-- into `subject_frag_id` would make a guess indistinguishable from a
-- person's own words for the rest of the corpus's life. So it lands here
-- instead, with the method that produced it and the confidence it carries,
-- and every consumer chooses whether to count it.
--
-- One row per (claim, role): a claim has at most one inferred subject and
-- at most one inferred object. Re-running an inference updates in place
-- rather than accumulating opinions.

CREATE TABLE IF NOT EXISTS claim_attributions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id      BIGINT NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    -- 'subject' or 'object'. Same vocabulary as the claim columns.
    role          TEXT   NOT NULL CHECK (role IN ('subject', 'object')),
    fragrance_id  BIGINT NOT NULL REFERENCES fragrances(id),
    -- How this was decided. A string rather than an enum so a new method
    -- does not need a migration; the aggregation layer filters on it.
    method        TEXT   NOT NULL,
    -- What the method saw. For 'video_subject' this is the video id and the
    -- title or query the subject was read out of, so a person auditing a
    -- row does not have to re-derive it.
    evidence      TEXT   NOT NULL DEFAULT '',
    -- Measured, not asserted: the sampled accuracy of the method that wrote
    -- this row, at the time it wrote it.
    confidence    DOUBLE PRECISION NOT NULL,
    -- 'proposed' until a person or an evaluation accepts it. Nothing
    -- declarative may rest on 'proposed' rows; retrieval may.
    review_status TEXT   NOT NULL DEFAULT 'proposed'
                  CHECK (review_status IN ('proposed', 'accepted', 'rejected')),
    created_at    TEXT   NOT NULL,
    UNIQUE (claim_id, role)
);

CREATE INDEX IF NOT EXISTS idx_attributions_fragrance
    ON claim_attributions (fragrance_id, review_status);
CREATE INDEX IF NOT EXISTS idx_attributions_method
    ON claim_attributions (method, review_status);
