-- Vectors for the descriptor text people actually wrote.
--
-- `vector` is a `double precision[]`, not a pgvector column. Two reasons,
-- both measured rather than assumed:
--
--   1. pgvector is not installed in this PostgreSQL and cannot be assumed
--      present on a laptop that clones this repo. `SELECT * FROM
--      pg_available_extensions WHERE name = 'vector'` returns nothing here.
--   2. The corpus holds ~700 attribute facts. Brute-force cosine over 700
--      short vectors is microseconds in Python. An ANN index is a solution
--      to a problem this corpus does not have, and adding an extension
--      dependency to avoid a millisecond is the wrong trade.
--
-- The upgrade path is deliberate and cheap: when the corpus outgrows brute
-- force, `ALTER TABLE ... ALTER COLUMN vector TYPE vector(N)` with the
-- extension installed, and only `semantic.nearest` changes. Nothing else
-- reads this column.
--
-- `model` and `dim` are stored per row rather than assumed globally so a
-- corpus embedded with two models is detectable instead of silently
-- comparing vectors from different spaces — which produces plausible
-- nonsense rather than an error.

CREATE TABLE IF NOT EXISTS evidence_embeddings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- What was embedded. Always text a human wrote, never a generated
    -- summary: a vector of something a model invented would let invented
    -- language retrieve real bottles.
    kind        TEXT   NOT NULL CHECK (kind IN ('claim', 'fact')),
    -- For 'claim', the claims.id. For 'fact', the fragrance id.
    ref_id      BIGINT NOT NULL,
    -- The exact string embedded, kept so a match can be shown verbatim.
    text        TEXT   NOT NULL,
    model       TEXT   NOT NULL,
    dim         INTEGER NOT NULL,
    vector      DOUBLE PRECISION[] NOT NULL,
    created_at  TEXT   NOT NULL,
    UNIQUE (kind, ref_id, model)
);

CREATE INDEX IF NOT EXISTS idx_embeddings_model
    ON evidence_embeddings (model, kind);
