-- Fragrances the world has announced, tracked from rumour to evidence.
--
-- The point of this table is a distinction the rest of the system depends
-- on: **an announcement is discovery provenance, never smell evidence.**
-- A press release saying "notes of raspberry and vanilla" tells us a
-- bottle exists and what its house claims. It tells us nothing about what
-- anybody smelled, and it must never be able to become "people say this
-- smells of raspberry". So release rows live here, apart from `claims`,
-- and nothing in this table is readable by the evidence layer.
--
-- The second reason it exists is money. A newly announced fragrance has no
-- discussion yet, and extraction costs real money per comment. Spending it
-- the day a bottle is announced buys silence. The lifecycle below is a
-- machine for waiting: discover cheaply, probe cheaply, and only reach for
-- the LLM once enough independent people are actually talking.

CREATE TABLE IF NOT EXISTS release_candidates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Where this came from. `source_type` is the adapter class
    -- ('rss', 'retailer_feed', 'brand_announcement', 'fixture'), and
    -- `source_id` is that source's own identifier for the item, so the
    -- same announcement seen twice is one row.
    source_type    TEXT NOT NULL,
    source_id      TEXT NOT NULL,
    source_url     TEXT NOT NULL DEFAULT '',

    -- What the source said. Deliberately kept as the source wrote it: the
    -- resolver decides what it maps to, and overwriting the original text
    -- destroys the only record of what was actually announced.
    brand          TEXT NOT NULL DEFAULT '',
    name           TEXT NOT NULL,
    release_date   TEXT,

    -- Set once this candidate resolves to a catalogue row. NULL until
    -- then, which is what makes "unresolved" a state rather than a guess.
    fragrance_id   BIGINT REFERENCES fragrances(id),

    status         TEXT NOT NULL DEFAULT 'DISCOVERED'
                   CHECK (status IN ('DISCOVERED', 'VERIFIED', 'CATALOGED',
                                     'WAITING_FOR_DISCUSSION', 'ENRICHABLE',
                                     'EVIDENCED', 'REJECTED')),
    -- Why a human or a rule moved it, so a lifecycle can be read back.
    status_reason  TEXT NOT NULL DEFAULT '',

    first_seen     TEXT NOT NULL,
    last_seen      TEXT NOT NULL,

    -- Readiness probing. `relevant_creators` is the number that decides
    -- whether enrichment is worth paying for; `relevant_videos` is
    -- recorded but deliberately not the gate, because eight videos from
    -- one channel is one room talking to itself.
    last_probe_at    TEXT,
    next_probe_at    TEXT,
    probe_count      INTEGER NOT NULL DEFAULT 0,
    relevant_videos  INTEGER NOT NULL DEFAULT 0,
    relevant_creators INTEGER NOT NULL DEFAULT 0,

    UNIQUE (source_type, source_id)
);

CREATE INDEX IF NOT EXISTS idx_releases_status
    ON release_candidates (status, next_probe_at);
CREATE INDEX IF NOT EXISTS idx_releases_fragrance
    ON release_candidates (fragrance_id);
