-- Fragrance houses, curated once from Wikidata rather than pipeline-derived.
--
-- `data/curation/houses.jsonl` is a committed, one-time batch of 204 houses
-- pulled from Wikidata under CC0 and matched to this corpus by hand — see
-- `fragrance_graph.houses` for the import and `data/curation/VERIFICATION.md`
-- for how each match was made. This table exists so the resolver can ask
-- "is <X> a real fragrance house" without a network call, most immediately
-- for the trailing-"by <brand>" fix in `resolve.names` (see
-- data/experiments/delina-resolution-loss.md).
--
-- Same two guards migration 0009 put on `fragrances`, for the same reason:
-- nothing enforces uniqueness at the application layer, `import_houses` is
-- a plain upsert, and a second row for one house would split resolution
-- silently rather than failing loudly.
CREATE TABLE IF NOT EXISTS houses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The JSONL's own key. Stable across re-imports, unlike `id`, which is
    -- why upserts key on this rather than on name — a corrected spelling
    -- must update the existing row, not orphan it and insert a second one.
    house_id              TEXT NOT NULL,
    name                  TEXT NOT NULL,
    category              TEXT NOT NULL DEFAULT '',
    wikidata_qid          TEXT,
    official_website      TEXT,
    -- Nullable, unlike `release_candidates.source_url`: that column is
    -- always filled in by application code (`ReleaseItem.url` defaults to
    -- ""), while 43 of 204 rows in houses.jsonl genuinely have no source
    -- URL — Wikidata had no matching item to link to. NOT NULL DEFAULT ''
    -- would have rejected the import outright rather than record that.
    source_url            TEXT,
    resolution_status     TEXT NOT NULL DEFAULT '',
    match_basis           TEXT NOT NULL DEFAULT '',

    -- 'publish' (122) is fit for display on the site; 'review' (82) is
    -- not — but resolution is an internal use, not a display one, and
    -- `known_house_names` deliberately ignores this column. See its
    -- docstring for why a house nobody has cleared to show on a page is
    -- still real enough to justify stripping it off the end of a mention.
    publish_status        TEXT NOT NULL DEFAULT 'review'
                          CHECK (publish_status IN ('publish', 'review')),
    wikidata_description  TEXT,

    UNIQUE (house_id)
);

-- Case-insensitive for the same reason `idx_fragrances_canonical_name` is:
-- "Maison Alhambra" and "maison alhambra" are one house, and two rows
-- differing only by case would let the resolver see one of them and miss
-- the other depending on which query happened to run.
CREATE UNIQUE INDEX IF NOT EXISTS idx_houses_name
    ON houses (lower(name));
