-- Event-sourced state for the FACET service layer (fragrance_graph.api /
-- fragrance_graph.session). A session is one person's discovery
-- conversation — "I love Delina but the rose is too strong", a LOVE on a
-- sprayed bottle, a chip click — and every one of those is an event, never
-- an update to a mutable "current preferences" row. `session.rebuild`
-- replays a session's events in order to reconstruct its state, which is
-- the same reasoning the corpus itself runs on: the log is the truth, and
-- "current state" is a view computed from it, not a second copy that can
-- drift from it.
--
-- Deliberately operational, not corpus. `data/corpus/*.jsonl` is durable,
-- committed, and rebuilds the recommendation database from nothing; a
-- shopper's session on a kiosk is neither reusable corpus evidence (nobody
-- claimed anything a claim-extraction pass could grade) nor something a
-- rebuilt-from-scratch database should ever come back with — see
-- `fragrance_graph.corpus`'s comment near `CURATED_INPUT_TABLES` for where
-- this table would have been named if it belonged there, and why it isn't.
CREATE TABLE IF NOT EXISTS discovery_sessions (
    id          UUID PRIMARY KEY,
    -- 'unknown' rather than NULL: every session was started by *something*,
    -- and a caller that has not said which yet is a fact worth keeping
    -- distinct from a caller that said "I don't know".
    mode        TEXT NOT NULL DEFAULT 'unknown'
                CHECK (mode IN ('associate', 'self_serve', 'unknown')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Append-only. Nothing in fragrance_graph.api ever UPDATEs or DELETEs a
-- row here — `updated_at` on the parent session is the only thing a
-- later event touches on an earlier row, and that is on the *session*,
-- not on any event itself.
CREATE TABLE IF NOT EXISTS session_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  UUID NOT NULL REFERENCES discovery_sessions(id) ON DELETE CASCADE,
    -- 'say' (free text), 'prefs' (chip: attribute+direction, or occasion,
    -- or budget), 'feedback' (fragrance_id + verdict). See
    -- `fragrance_graph.session.rebuild` for the exact payload shape each
    -- kind carries and how it is replayed.
    kind        TEXT NOT NULL,
    payload     JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Replay reads one session's events in the order they were written.
-- `id` is the tiebreaker for events sharing a `created_at` timestamp
-- (multiple events can land in the same millisecond under a fast client),
-- and it is monotonic with insertion order here specifically because this
-- table is never updated in place — an ordinary sequence works as a
-- reliable "as-written" order only because of that append-only guarantee.
CREATE INDEX IF NOT EXISTS idx_session_events_session
    ON session_events (session_id, id);
