-- Retailer catalog listings: what a retailer sells, and what it costs —
-- never what its marketing copy says about it.
--
-- The pipeline these two tables sit at the end of:
--
--     raw Bright Data JSON  --(retail ingest)-->  data/curation/
--     retailer-listings.jsonl (facts + provenance, no description)
--                            --(retail import)-->  these tables
--
-- The raw scrape is not source of truth and never merges to main: it
-- carries the retailer's copyrighted marketing prose (`description`) and
-- customer reviews. The curated JSONL is the committed truth — facts a
-- machine can check (a title, a brand, a price, a size, a URL) plus
-- enough provenance to know where each fact came from — and these tables
-- are derived from it exactly the way `fragrances`/`claims` are derived
-- from `data/corpus/`: disposable, rebuilt by `retail import`, never a
-- second place a fact can drift from the file that actually means it.
-- See `fragrance_graph.retail`'s module docstring for the full argument.
--
-- Retailer-agnostic by construction. `retailer` is a column value, read
-- off each raw record's own `store_name`, not a table name or a schema
-- decision — Nordstrom is the first source ingested, and nothing below
-- assumes it is the only one, or the last.
CREATE TABLE IF NOT EXISTS retailer_listings (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    retailer               TEXT NOT NULL,
    retailer_item_id       TEXT NOT NULL,
    url                    TEXT NOT NULL,
    -- "_raw" on purpose: verbatim from the retailer, never normalised in
    -- place. `retail.strip_concentration_suffix` computes a resolution
    -- candidate from this at read time; nothing here overwrites it.
    title_raw              TEXT NOT NULL,
    brand_raw               TEXT NOT NULL DEFAULT '',

    -- NULL until the resolution pass links this listing to a catalogue
    -- bottle, and NULL again — never a guess — when it cannot be linked
    -- conservatively. See `retail.resolve_listings`: a listing must never
    -- resolve to a fragrance whose brand disagrees with `brand_raw`.
    fragrance_id            BIGINT REFERENCES fragrances(id),

    image_url                TEXT,
    -- A JSON array of URLs, same reasoning as `fragrances.aliases`: a
    -- curator or a future reconciliation pass can read it without
    -- learning a second table shape for "a list of strings".
    additional_image_urls    JSONB NOT NULL DEFAULT '[]',
    review_count              INTEGER,
    star_rating                NUMERIC,
    -- The retailer's own category string, kept whole ("Home>Beauty>
    -- Fragrance>Perfume") rather than split into a second table — it is
    -- read, not queried structurally, by `retail.is_fragrance` and by a
    -- curator eyeballing `retail unresolved`.
    category_path             TEXT NOT NULL DEFAULT '',
    retrieved_at               TEXT NOT NULL,

    -- Provenance for the argument this whole table's design rests on:
    -- which pipeline collected the row ('bright_data' today) and the
    -- legal basis that makes storing it acceptable
    -- ('facts_and_image_url_only' — see retail.py's RIGHTS_BASIS). Both
    -- are columns, not a comment, so a second collector or a future
    -- retailer with a different agreement is a new value here, not a
    -- silent assumption baked into application code.
    collection_mode            TEXT NOT NULL,
    rights_basis                TEXT NOT NULL,

    -- Always true for every row this pipeline writes today: an
    -- `image_url` is a link to the retailer's own hosted image, never a
    -- copy this codebase downloaded or re-hosts. A column rather than an
    -- assumption, so a future ingest path with different rights is a
    -- new value here rather than a silent reinterpretation of this one.
    image_ref_only              BOOLEAN NOT NULL DEFAULT TRUE,

    -- One row per (retailer, their own item id) — re-ingesting the same
    -- listing (a re-scrape, a price refresh) updates in place rather than
    -- duplicating, the same reasoning as `houses`' unique `house_id`.
    UNIQUE (retailer, retailer_item_id)
);

CREATE INDEX IF NOT EXISTS idx_retailer_listings_fragrance
    ON retailer_listings (fragrance_id);

-- One listing, several purchasable sizes. Bright Data's "size" variant
-- entries only — "color"/"NO COLOR" entries are packaging noise with no
-- fact of their own to record; see `retail.ingest`.
CREATE TABLE IF NOT EXISTS retailer_variants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id     BIGINT NOT NULL REFERENCES retailer_listings(id) ON DELETE CASCADE,

    sku             TEXT NOT NULL,
    -- The retailer's own size string, verbatim ("6.8 Ounce", "1 Ounce
    -- Refill") — always kept, because `size_ml` is not always derivable
    -- from it and the display is the only size fact some rows will ever
    -- have.
    size_display     TEXT NOT NULL,
    -- NULL unless `size_display` already states an unambiguous metric
    -- size. Deliberately never computed from an ounce figure by a
    -- conversion formula: a bottle's "6.8 Ounce" label and its true
    -- manufactured metric size were rounded independently by whoever
    -- wrote each one, so multiplying back out produces a number that
    -- looks precise (201.1) and is not the bottle's actual labelled
    -- size. Wrong unit math here is worse than NULL — see
    -- `retail.parse_size_ml`.
    size_ml           NUMERIC,
    price_usd          NUMERIC,
    in_stock            BOOLEAN NOT NULL DEFAULT TRUE,
    retrieved_at         TEXT NOT NULL,

    -- One row per (listing, retailer SKU) — matches the natural key a
    -- re-ingest actually has: Bright Data's `option_id` is stable across
    -- a re-scrape of the same product, `size_display` is not guaranteed
    -- to be (a retailer could reword "6.8 Ounce" to "6.8 oz").
    UNIQUE (listing_id, sku)
);

CREATE INDEX IF NOT EXISTS idx_retailer_variants_listing
    ON retailer_variants (listing_id);
